### ISSUE TITLE
lambda-proxy sam build error

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-example-4j#657]
### sam build fails
```
$ sam build --debug
2021-01-29 14:18:56,285 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-01-29 14:18:56,362 | 'build' command is called
2021-01-29 14:18:56,376 | No Parameters detected in the template
2021-01-29 14:18:56,403 | 5 resources found in the template
2021-01-29 14:18:56,403 | Found Serverless function with name='PetsGetFunction' and CodeUri='PetsGetFunction'
2021-01-29 14:18:56,403 | Found Serverless function with name='PetsPostFunction' and CodeUri='PetsPostFunction'
2021-01-29 14:18:56,404 | Found Serverless function with name='PetsPetIdGetFunction' and CodeUri='PetsPetIdGetFunction'
2021-01-29 14:18:56,404 | Found Serverless function with name='PetsPetIdDeleteFunction' and CodeUri='PetsPetIdDeleteFunction'
2021-01-29 14:18:56,404 | No Parameters detected in the template
2021-01-29 14:18:56,430 | Instantiating build definitions
2021-01-29 14:18:56,448 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsGetFunction, Zip, , 4e4f1579-6c5e-4f3f-a793-e2f87d61c251, {}, []), Current: BuildDefinition(provided, PetsGetFunction, Zip, , 14ecf7ef-74a2-4a24-ad39-2ecec810c0d3, {}, []), Function: Function(name='PetsGetFunction', functionname='PetsGetFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsGetFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsGet': {'Type': 'Api', 'Properties': {'Path': '/v1/pets', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:18:56,449 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPostFunction, Zip, , 109ea2c7-4135-4086-a7e4-2ff551320616, {}, []), Current: BuildDefinition(provided, PetsPostFunction, Zip, , 586274ca-6404-452b-b315-a5a698a319c9, {}, []), Function: Function(name='PetsPostFunction', functionname='PetsPostFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPostFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPost': {'Type': 'Api', 'Properties': {'Path': '/v1/pets', 'Method': 'POST', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:18:56,449 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPetIdGetFunction, Zip, , 02fd07aa-2a03-46b6-81ba-282c36b46fb7, {}, []), Current: BuildDefinition(provided, PetsPetIdGetFunction, Zip, , 818de54f-a6c5-4a08-a740-59f9d77c82b6, {}, []), Function: Function(name='PetsPetIdGetFunction', functionname='PetsPetIdGetFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPetIdGetFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPetIdGet': {'Type': 'Api', 'Properties': {'Path': '/v1/pets/{petId}', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:18:56,449 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPetIdDeleteFunction, Zip, , 06b42b28-aa11-4b7b-9de9-b9245f25c8bc, {}, []), Current: BuildDefinition(provided, PetsPetIdDeleteFunction, Zip, , cf8c39ad-ddf5-4544-a422-13da63e2d44f, {}, []), Function: Function(name='PetsPetIdDeleteFunction', functionname='PetsPetIdDeleteFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPetIdDeleteFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPetIdDelete': {'Type': 'Api', 'Properties': {'Path': '/v1/pets/{petId}', 'Method': 'DELETE', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:18:56,450 | Building codeuri: PetsGetFunction runtime: provided metadata: {} functions: ['PetsGetFunction']
2021-01-29 14:18:56,450 | Building to following folder /home/balloon/workspaces/light-example-4j/lambda/petstore-proxy/.aws-sam/build/PetsGetFunction
2021-01-29 14:18:56,451 | Loading workflow module 'aws_lambda_builders.workflows'
2021-01-29 14:18:56,452 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-01-29 14:18:56,453 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-01-29 14:18:56,454 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-01-29 14:18:56,455 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-01-29 14:18:56,456 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-01-29 14:18:56,457 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-01-29 14:18:56,458 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-01-29 14:18:56,459 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-01-29 14:18:56,460 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-01-29 14:18:56,460 | Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'

Build Failed
2021-01-29 14:18:56,461 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 175, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': '8405f96f-6504-4450-afa8-ab19498e7bf2', 'installationId': 'c97b9f7e-e39a-4545-96f5-e968d5e5f65b', 'sessionId': 'c900642d-02d7-4d58-b150-aaad696a58cb', 'executionEnvironment': 'CLI', 'pyversion': '3.8.7', 'samcliVersion': '1.15.0'}}]}
2021-01-29 14:18:56,771 | Telemetry response: 200
Error: CustomMakeBuilder:Resolver - Path resolution for runtime: provided of binary: make was not successful
```
### Sam Version
```
$ sam --version
SAM CLI, version 1.15.0
```
### Java Version
```
$ java --version
openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
```
### Gradle Version
```
$ gradle --version

------------------------------------------------------------
Gradle 6.8.1
------------------------------------------------------------

Build time:   2021-01-22 13:20:08 UTC
Revision:     31f14a87d93945024ab7a78de84102a3400fa5b2

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.9 (Azul Systems, Inc. 11.0.9+11-LTS)
OS:           Linux 5.8.0-38-generic amd64
```
### Use "sam build -u --debug"
Technically the build container should have the env set up correctly.
```
$ sam build -u --debug
2021-01-29 14:24:05,077 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-01-29 14:24:05,154 | 'build' command is called
2021-01-29 14:24:05,154 | Starting Build inside a container
2021-01-29 14:24:05,168 | No Parameters detected in the template
2021-01-29 14:24:05,196 | 5 resources found in the template
2021-01-29 14:24:05,196 | Found Serverless function with name='PetsGetFunction' and CodeUri='PetsGetFunction'
2021-01-29 14:24:05,196 | Found Serverless function with name='PetsPostFunction' and CodeUri='PetsPostFunction'
2021-01-29 14:24:05,196 | Found Serverless function with name='PetsPetIdGetFunction' and CodeUri='PetsPetIdGetFunction'
2021-01-29 14:24:05,196 | Found Serverless function with name='PetsPetIdDeleteFunction' and CodeUri='PetsPetIdDeleteFunction'
2021-01-29 14:24:05,197 | No Parameters detected in the template
2021-01-29 14:24:05,223 | Instantiating build definitions
2021-01-29 14:24:05,242 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsGetFunction, Zip, , 4e4f1579-6c5e-4f3f-a793-e2f87d61c251, {}, []), Current: BuildDefinition(provided, PetsGetFunction, Zip, , 55041439-c79f-4818-a01c-2e953d6346f9, {}, []), Function: Function(name='PetsGetFunction', functionname='PetsGetFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsGetFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsGet': {'Type': 'Api', 'Properties': {'Path': '/v1/pets', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:24:05,243 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPostFunction, Zip, , 109ea2c7-4135-4086-a7e4-2ff551320616, {}, []), Current: BuildDefinition(provided, PetsPostFunction, Zip, , 8c8cad11-128a-41b9-ab8f-23b696748758, {}, []), Function: Function(name='PetsPostFunction', functionname='PetsPostFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPostFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPost': {'Type': 'Api', 'Properties': {'Path': '/v1/pets', 'Method': 'POST', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:24:05,243 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPetIdGetFunction, Zip, , 02fd07aa-2a03-46b6-81ba-282c36b46fb7, {}, []), Current: BuildDefinition(provided, PetsPetIdGetFunction, Zip, , 50e40996-27a7-4ddb-8321-c8ecb59fc934, {}, []), Function: Function(name='PetsPetIdGetFunction', functionname='PetsPetIdGetFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPetIdGetFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPetIdGet': {'Type': 'Api', 'Properties': {'Path': '/v1/pets/{petId}', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:24:05,243 | Same function build definition found, adding function (Previous: BuildDefinition(provided, PetsPetIdDeleteFunction, Zip, , 06b42b28-aa11-4b7b-9de9-b9245f25c8bc, {}, []), Current: BuildDefinition(provided, PetsPetIdDeleteFunction, Zip, , 5bf8fe0e-2b01-4bff-8806-5662a1cb4c05, {}, []), Function: Function(name='PetsPetIdDeleteFunction', functionname='PetsPetIdDeleteFunction', runtime='provided', memory=512, timeout=20, handler='com.networknt.petstore.handler.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='PetsPetIdDeleteFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'PetsPetIdDelete': {'Type': 'Api', 'Properties': {'Path': '/v1/pets/{petId}', 'Method': 'DELETE', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, codesign_config_arn=None))
2021-01-29 14:24:05,244 | Building codeuri: PetsGetFunction runtime: provided metadata: {} functions: ['PetsGetFunction']
2021-01-29 14:24:05,244 | Building to following folder /home/balloon/workspaces/light-example-4j/lambda/petstore-proxy/.aws-sam/build/PetsGetFunction

Fetching amazon/aws-sam-cli-build-image-provided Docker container image......
2021-01-29 14:24:05,999 | Mounting /home/balloon/workspaces/light-example-4j/lambda/petstore-proxy/PetsGetFunction as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Running workflow 'CustomMakeBuilder'
Running CustomMakeBuilder:CopySource
CustomMakeBuilder:CopySource succeeded
Running CustomMakeBuilder:MakeBuild
Current Artifacts Directory : /tmp/samcli/artifacts
executing Make: ['make', '--makefile', '/tmp/samcli/source/Makefile', 'build-PetsGetFunction']
CustomMakeBuilder:MakeBuild failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 94, in execute
    cwd=self.scratch_dir,
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/make.py", line 88, in run
    raise MakeExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.custom_make.make.MakeExecutionError: Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 97, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 94, in execute
    cwd=self.scratch_dir,
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/make.py", line 88, in run
    raise MakeExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.custom_make.make.MakeExecutionError: Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 97, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib64/python3.6/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: CustomMakeBuilder:MakeBuild - Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1
2021-01-29 14:24:14,783 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "CustomMakeBuilder:MakeBuild - Make Failed: FAILURE: Build failed with an exception.\n\n* What went wrong:\nCould not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().\n> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 7s\nmake: *** [build-PetsGetFunction] Error 1"}}

Build Failed
2021-01-29 14:24:15,483 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 10405, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': '1b06e032-1369-4e16-9203-13b325a83faa', 'installationId': 'c97b9f7e-e39a-4545-96f5-e968d5e5f65b', 'sessionId': '60209364-a6e4-4ab2-9a73-39c74f793b89', 'executionEnvironment': 'CLI', 'pyversion': '3.8.7', 'samcliVersion': '1.15.0'}}]}
2021-01-29 14:24:15,784 | Telemetry response: 200
Error: CustomMakeBuilder:MakeBuild - Make Failed: FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
make: *** [build-PetsGetFunction] Error 1
```

**Comment by BalloonWen** [comment]
it was because of missing "make" command in linux
Based on
https://github.com/aws/aws-lambda-builders/blob/67f42dd936fd4f0c517c38acb8b6a170156549ec/aws_lambda_builders/workflows/custom_make/workflow.py#L58
it tries to use make binary which could not be found, so make sure you have the "make" command
